### ISSUE TITLE
Make the Code PSR-2 compliant

### ISSUE THREAD

**Issue by daudmalik06** [daudmalik06/PhpChromeToPdf#11]
Make the code PSR-2 compliant 
i.e change some parenthesis etc ...

**Comment by tophcodes** [comment]
I'll gladly take a look at this one

**Comment by daudmalik06** [comment]
@padarom thanks ,

**Comment by alexsoft** [comment]
@daudmalik06 Why not just use https://styleci.io/? I can make PR with config file and you will only need to activate it.

UPD: I already have made a PR #13 with added config

**Comment by daudmalik06** [comment]
@alexsoft  good idea , but the problem is the current code isn't properly psr-2 compliant , 
so have to make it compliant then for future let's stick with your idea of styleci

Thanks

**Comment by alexsoft** [comment]
You can just run a style ci check on current code base and it will fix everything via pull request. We can talk in private, so I can help you with it, if you want.

**Comment by daudmalik06** [comment]
thanks @alexsoft  thanks, you can message me at daudmalik06@gmail.com
