### ISSUE TITLE
verify installation of chrome 

### ISSUE THREAD

**Issue by daudmalik06** [daudmalik06/PhpChromeToPdf#16]
on linux/mac we are successfully verifying installation of chrome , but on windows we have to do it , 
we are using method called `abortIfChromeIsNotInstalled` 
which verifies chrome installation , and throws exception if chrome is not installed.

**Comment by olivernybroe** [comment]
@daudmalik06 have you considered just adding the chromedriver files to the project, so it always has a version available? 
https://sites.google.com/a/chromium.org/chromedriver/

**Comment by daudmalik06** [comment]
@uruloke  actually i saw that too , but problem is by doing so we will end up using 2 binaries for such small package , and i don't want user to install just one more library just to check if he has installed another library correctly , 
what do you think ?

**Comment by olivernybroe** [comment]
@daudmalik06 Getting a little out of the original issue.
If we put he binaries in, we would prob. need 3 versions, and yeah it would add up the size a lot, like 25 mb or so, we do however then have an easy to install package. 

Another solution would be (which I think I like the most) to have a second repo which contains the binaries. Then in your composer add that binary in as a suggestion, so when we install the package it suggests us to install the binary with it for ease of use.

**Comment by daudmalik06** [comment]
yeah we can try it we don't find simple solutions , 
right now we have problem only with windows 
i don't think it would be great problem 
on windows one could check if running any binary didn't give ` not found error ` means that binary is present ,
