### ISSUE TITLE
Website behind login form

### ISSUE THREAD

**Issue by antton** [daudmalik06/PhpChromeToPdf#19]
Hi, could you make an example of how to login in a website, take the cookie and then take the screenshot?

I think it would be really interesting in general.

Thanks!

**Comment by daudmalik06** [comment]
hello , i am working on this ,

**Comment by sagar117** [comment]
Do you want to make a login form too?

**Comment by daudmalik06** [comment]
@sagar117  it's not what you understood , 
read the issue again.

**Comment by sagar117** [comment]
@daudmalik06  Elaborate, please

**Comment by antton** [comment]
Hi,

Sorry for the delay, I have a Joomla instalation and I would like to login on the admin panel and take screenshots of some private URLs, that's why I need to be able of login and keep the cookies also Joomla at least use some hidden token inputs with in the form and we need to send it as well.

I don't know if it's elaborate enough.

Thanks!

**Comment by daudmalik06** [comment]
@antton yeah the main problem is with token , 
and chrome headless doesn't allow us to do further actions 
1 solution can be login to site using guzzle and then grab html from there and use it here , 
what do you think
