### ISSUE TITLE
Getting Stuck - Timeout Argument Ignored

### ISSUE THREAD

**Issue by robc72** [daudmalik06/PhpChromeToPdf#24]
The url specified gets stuck and won't timeout. Did I do something wrong?
Thanks,
Rob

// THIS IS THE PROBLEM URL
$url = "https://www.shutterstock.com/en/editor/template/6036521";

$chrome = new Chrome($url, "/usr/bin/google-chrome");
$chrome->setArguments([
	'--timeout' => 6000
]);
$chrome->setWindowSize($width=1280,$height=800);
$chrome->getScreenShot("/home/screenshots/sample.jpg");

// CODE NEVER GETS HERE

echo "I made it here";

**Comment by daudmalik06** [comment]
hey @robc72  
did you try any example mentioned e.g ,
    
    $chrome=new Chrome(null,'/usr/bin/google-chrome');
    $chrome->useHtml("<h2>I am test html</h2>");
    print "Pdf successfully generated :".$chrome->getPdf("/tmp/mypdf.pdf").PHP_EOL;
    print "screenShot successfully generated :".$chrome->getScreenShot("/tmp/hello/test.jpg").PHP_EOL;

and did you verify the installation of chrome if that works from bash ??
please provided little environment details , so that i can debug that
thanks

**Comment by robc72** [comment]
The test works fine when I use a different save path. When using the /tmp/ is hangs just like with that once bad url.

https://www.shutterstock.com/en/editor/template/6036521
Just so you know the rest of the urls I've tried are working fine.

The PDF generated has some bad fonts/garbled text which is another entirely different issue for me so if you have some insight there as well I would really appreciate it. The areas with the bad font are the date at the top and the url and page at the bottom.

I'm hosting on Centos 7 and NGINX. Please let me know if there's any other information you need.

**Comment by robc72** [comment]
It appears that --ipc-connection-timeout does the trick for the timeout but that doesn't explain the problem of the page not loading for that specific url.

Well the page is loading correctly now after adding that so this may not be an issue anymore.

**Comment by daudmalik06** [comment]
awesome , 
i am happy your issue is resolved ,
happy coding :)
