### ISSUE TITLE
Arguments --dump-dom and --dump-html

### ISSUE THREAD

**Issue by robc72** [daudmalik06/PhpChromeToPdf#25]
Will this support arguments like --dump-dom and --dump-html? I've been messing with it without any luck at all. Hoping I'm just doing something wrong. Having a hard time finding any docs on these.

Tried like...

$chrome->setArguments([
	'--dump-html' => '',
]);

and also

$chrome->setArguments([
	'--dump-html' => '/home/screenshots/test.html',
]);

But neither output anything. At least where I was looking for it anyway.

Thanks,
Rob

**Comment by daudmalik06** [comment]
@robc72  hey , until now i haven't added these features , but i assure you this will be added in next release
thanks

**Comment by robc72** [comment]
Awesome, thank you. Is there anything I can do to get that accelerated?

**Comment by daudmalik06** [comment]
yeah , if you can implement that and send a PR , it would be appreciated 

thanks
