### ISSUE TITLE
Print page in landscape

### ISSUE THREAD

**Issue by amrography** [daudmalik06/PhpChromeToPdf#28]
Hi, 

How can I print web page in landscape mode ?
I tried to extend the argument `--print-to-pdf=landscape` after file name from `getPdf` method butt didn't work

**Comment by daudmalik06** [comment]
Hello, you might have resolved the issue, but I'm answering for the benefit of others as it might be useful to them:

You can achieve this using the `setArguments` method as follows:

```php
$chrome->setArguments(["--print-to-pdf-params" => "'{\"landscape\": true}'"]);
```

Thanks.
