### ISSUE TITLE
remove printed header and footer

### ISSUE THREAD

**Issue by Bigben83** [daudmalik06/PhpChromeToPdf#29]
is there some argument that can be added to remove the printed header and footer information on the pdf, like the date at the top and the url at the bottom.

**Comment by Vimalsumanthran** [comment]
Got any solution?

**Comment by romain-le-mercier** [comment]
Up, would be nice to have.
EDIT : Found the solution, add this in your css : 
`@page { 
     margin: 0;
     size: auto;
 }`
Credit & source : 
https://support.google.com/chrome/forum/AAAAP1KN0B0LBMUDtGqr-0/?hl=fa
https://stackoverflow.com/questions/44575628/alter-the-default-header-footer-when-printing-to-pdf
