### ISSUE TITLE
Setting Paper Size

### ISSUE THREAD

**Issue by Bigben83** [daudmalik06/PhpChromeToPdf#31]
Is there a command to set the paper size of the pdf produced?
e.g. A4 or A3

**Comment by daudmalik06** [comment]
Hello, you may have already resolved the issue, but I'm answering anyway for others who are looking for a solution. You can achieve this with the `$chrome->setWindowSize` method. For example, for an A4 size, you can use:

```php
// A4
$chrome->setWindowSize(794, 1983);

// For A3
$chrome->setWindowSize(1122, 1587);
```

Thanks.
