### ISSUE TITLE
Print current and total page number value in repeatable custom header at custom position

### ISSUE THREAD

**Issue by wpteam4** [daudmalik06/PhpChromeToPdf#32]
Hello Team,

How can we print current and total page number value in the repeatable custom header at custom position.

Thanks
![sample](https://user-images.githubusercontent.com/5585625/110077120-9c4b6b00-7dab-11eb-93ff-975a6f2386cb.png)

**Comment by wpteam4** [comment]
Code I'm using:

use dawood\phpChrome\Chrome; 


$chrome=new Chrome('https://youtube.com','/usr/bin/google-chrome');
$chrome->setOutputDirectory(__DIR__);
//not necessary to set window size
$chrome->setWindowSize($width=1477,$height=768);
print "Pdf successfully generated :".$chrome->getPdf().PHP_EOL;

**Comment by daudmalik06** [comment]
Hello, although this is a bit old, I'm answering it anyway as it might be useful for others.

Directly setting headers and footers with this library is not possible, but it can be achieved using CSS print queries. Here's an example:

```<html>
<head>
    <style>
        @media print {
            .header {
                position: fixed;
                top: 0;
                width: 100%;
                text-align: center;
            }
            .footer {
                position: fixed;
                bottom: 0;
                width: 100%;
                text-align: center;
            }
        }
    </style>
</head>
<body>
    <div class="header">This is the header</div>
    <div class="content">Your page content here</div>
    <div class="footer">This is the footer</div>
</body>
</html>
```
