### ISSUE TITLE
download pdf

### ISSUE THREAD

**Issue by xavikhattak** [daudmalik06/PhpChromeToPdf#4]
hello
I want to use this library but i want when user access my page e.g example.com?url=http://googel.com 
i download the pdf of google.com on his browser 
how to do that ?

**Comment by daudmalik06** [comment]
Hello @xavikhattak  you have to send proper header from php ,
```php
header("Content-type:application/pdf");

// It will be called downloaded.pdf
header("Content-Disposition:attachment;filename='downloaded.pdf'");

// The PDF source is in original.pdf
readfile("original.pdf");

```
but i am working to implement this method too i.e `download` etc ...
hope it solved this issue.
Thanks ,

**Comment by xavikhattak** [comment]
thanks i understood it would be awesome to add that feature ...
