### ISSUE TITLE
PHP7 and PHPUnit

### ISSUE THREAD

**Issue by jakenoble** [daudmalik06/PhpChromeToPdf#5]
Is there a way of having this run on PHP5.6? I cannot install it because....

> Problem 1
>     - phpunit/phpunit 6.2.3 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
>     - phpunit/phpunit 6.2.2 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
>     - phpunit/phpunit 6.2.1 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
>     - phpunit/phpunit 6.2.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
>     - dawood/phpchromepdf v1.2 requires phpunit/phpunit ^6.2 -> satisfiable by phpunit/phpunit[6.2.0, 6.2.1, 6.2.2, 6.2.3].
>     - Installation request for dawood/phpchromepdf ^1.2 -> satisfiable by dawood/phpchromepdf[v1.2].
>

**Comment by daudmalik06** [comment]
hey 
just resolved this issue in [Release v1.3](https://github.com/daudmalik06/PhpChromeToPdf/releases/tag/v1.3)
try this way  

`composer require dawood/phpchromepdf:1.3`

in case you want to import  phpunit too
you can require this with dev

hope it will resolve your problem
Best Regards

**Comment by jakenoble** [comment]
Great thanks!
