### ISSUE TITLE
Mac OS binary

### ISSUE THREAD

**Issue by jakenoble** [daudmalik06/PhpChromeToPdf#6]
Is there a way to use this on Mac, the apt-get instructions fail on Mac, of course, and this fails too

    $chrome=new Chrome(null,'/Applications/Google\ Chrome.app');

**Comment by jakenoble** [comment]
I have fixed this now. For others you have to reference the exec inside the .app folder.

In my case I copied the .app file and then renamed it to google-chrome and then reference it like so

    $chrome =new Chrome(null,'/Users/joebloggs/Desktop/google-chrome/Contents/MacOS/Google\ Chrome');

**Comment by daudmalik06** [comment]
thanks buddy
