### ISSUE TITLE
PDF generating but exception is thrown

### ISSUE THREAD

**Issue by KKSzymanowski** [daudmalik06/PhpChromeToPdf#7]
Hi,

I'm trying out your package on Windows 10 and the first thing I ran into was when I run:

```php
use dawood\phpChrome\Chrome;

$url = 'https://google.com';
$exePath = 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe';

$chrome = new Chrome($url, $exePath);
$chrome->setOutputDirectory(__DIR__);
echo 'Pdf successfully generated :' . $chrome->getPdf();
```

the PDF file is generated within a couple of seconds and saved in the working directory with a seemingly random name(like `110b324cc2ba9e30d781b22e289d212b.pdf`). The script however ends execution after 34 seconds with the following error:

![image](https://user-images.githubusercontent.com/13980973/30169013-6ca2d896-93eb-11e7-9420-eed281c497b4.png)

There are a couple of things I checked:
1. Switching `mikehaertl\shellcommand\Command::$useExec` to `true` doesn't change a thing.
2. When I examine the exit code of the command it's a very big negative number, suggesting some memory leak.
3. In `C:\Program Files (x86)\Google\Chrome\Application\debug.log` there are three lines for each PDF generation request:
```
[0907/163002.784:ERROR:process_info.cc(632)] range at 0x5109352000000000, size 0x238 fully unreadable
[0907/163002.784:ERROR:process_info.cc(632)] range at 0x5109352200000000, size 0x238 fully unreadable
[0907/163002.784:ERROR:process_info.cc(632)] range at 0x0, size 0x238 fully unreadable

[0907/163220.995:ERROR:process_info.cc(632)] range at 0xd3f9357000000000, size 0x21e fully unreadable
[0907/163220.995:ERROR:process_info.cc(632)] range at 0xd3f9357200000000, size 0x21e fully unreadable
[0907/163220.995:ERROR:process_info.cc(632)] range at 0x0, size 0x21e fully unreadable

[0907/163840.507:ERROR:process_info.cc(632)] range at 0x4a79341000000000, size 0x110 fully unreadable
[0907/163840.507:ERROR:process_info.cc(632)] range at 0x4a79341200000000, size 0x110 fully unreadable
[0907/163840.507:ERROR:process_info.cc(632)] range at 0x0, size 0x110 fully unreadable
```
4. When I run the generated command directly in the CMD it exits immediately with code `0` and the PDF file appears in the desired location couple of seconds later.
```
C: && cd "C:\Program Files (x86)\Google\Chrome\Application" && chrome.exe --print-to-pdf="C:\server\projects\popc\routes/bb1b4f996c2d5431b60c247ac7150a201.pdf" --headless --disable-gpu --incognito --enable-viewport https://google.com
```
5. If I run the same PHP code via CLI(CMD or Powershell) a new browser window opens(despite the presence of `--headless` flag) but other than that it behaves just like ran from the browser(file generated after several seconds and script exiting after 34 seconds with an exception).

I'm using:
- Windows 10 Pro 1703 Build 15063.540 64bit
- Google Chrome 60.0.3112.113 64bit
- PHP 7.1.1 ZTS MSVC14 64bit

Have you ran into something similar and found a solution?

**Comment by KKSzymanowski** [comment]
My Chrome just updated itself to `61.0.3163.79`, the issue is gone.

**Comment by daudmalik06** [comment]
i am glad that it resolved your issue , and finally we know working version of chrome too (for windows)
,now have to update the docs.

thanks for reporting that :)

**Comment by KKSzymanowski** [comment]
Now that you're here 😄, do you know how I can disable the default header and footer? I have looked all over the web but couldn't find a solution.
