### ISSUE TITLE
add Separate Config file 

### ISSUE THREAD

**Issue by daudmalik06** [daudmalik06/PhpChromeToPdf#9]
Add separate config file for the library 
now we are using hard coded configuration , the idea is to pluck them out
and use a single config file e.g 

the binary path
the output path
can be anything that we are currently using in library

structure should be 
`library / src / config .php` 
Thanks

**Comment by simonstaton** [comment]
Working on this now

**Comment by daudmalik06** [comment]
@simonstaton  thanks buddy 
don't forget to check [Contibution guide](https://github.com/daudmalik06/PhpChromeToPdf/blob/master/CONTRIBUTING.md)

**Comment by daudmalik06** [comment]
@simonstaton  
sorry had to change little description of the issue ,
hope you can understand.

**Comment by simonstaton** [comment]
@daudmalik06 how's this? https://github.com/daudmalik06/PhpChromeToPdf/pull/10

**Comment by daudmalik06** [comment]
@simonstaton  thanks for quick  response ,
but unfortunately there are many things missing like output directory but that's not big deal , 
if it's possible can you try like laravel's config e.g [session config](https://github.com/laravel/laravel/blob/master/config/session.php)

and then require those config like laravel does


$config=require 'config.php';
and then set these configuration if necessary 
and have to pluck out necessary config (present in constructor) .

Thanks

**Comment by daudmalik06** [comment]
@simonstaton  can you check [ coding standard ](https://github.com/daudmalik06/PhpChromeToPdf/commit/0590ebf7a6abcc31884c2cb37fb63d17b9ed9201)
i know the existing code need to be converted in psr-2

**Comment by simonstaton** [comment]
@daudmalik06 I have updated to be simpler following the laravel example, you can check the original pr
